[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
supabased-proto = { path = "crates/supabased-proto" }
tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
clap = { version = "4.6.0", features = ["derive"] }
tonic-prost-build = "0.14"
protoc-bin-vendored = "3"
